project:
  type: website

website:
  title: "Estatística Básica"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - lista.qmd
      - tabs.Rmd
      - DistrNormal.Rmd
      - benford.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

